server:
  port: 7083
spring:
  application:
    name: log-transformer
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chocolatedisco?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  aop:
    auto: true
    proxy-target-class: true
  redis:
    host: 192.40.10.11
    port: 6379
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    status-page-url-path: /application/info
    health-check-url-path: /application/health
  client:
    service-url:
      defaultZone: http://127.0.0.1:10080/eureka/
endpoints:
  health:
    id: health
    sensitive: false
    enabled: true
  mappings:
    id: mappings
    sensitive: false
    enabled: true
  info:
    id: info
    sensitive: false
    enabled: true
info:
  app:
    name: 日志采集配置管理工程
    version: 1.0